[project]
name = "smores"
version = "0.1.0"
description = "Simulator for Modular Recommendation EcoSystems"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "icecream>=2.1.4",
    "lenskit @ git+https://github.com/lenskit/lkpy@3ed6c726f663e56288110d5d34b20c976e1e7f28",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pyarrow>=18.0.0",
    "pydantic>=2.11.4",
    "pyyaml>=6.0.2",
]

[project.optional-dependencies]
implicit = ["implicit>=0.7.2"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["smores"]
exclude = ["data"]
