# Sample SMORES configuration
# TODO: Where to specific data sharing behavior

simulation:
    experiment_name: test_experiment
    num_days: 10
    num_cycles: 10
    slate_size: 5
    seed: 20250513

data:
  directory: data/raw/ambar
  consumer_file: users.csv
  item_file: items.csv
  provider_file: artists.csv

  initial_recommender_assignment:
    class_name: fixed
    name: Generic

consumers:
  - consumer_type: Generic
    utility_model:
    class_name: list_average

    item_selection_model:
      class_name: category_similarity_logit
      threshold: 0.3

    recommender_choice_model:
      class_name: fixed
      recommender_name:  Generic

  - consumer_type: Niche


provider:
  utility_model:
    class_name: click_fixed
    value: 1

platform:
  utility_model:
    class_name: null_model

recommenders:
  - name: Generic
    class_name: item_knn_cold
    min_neighbors: 1
    max_neighbors: 20
    min_similarity: 0.001
    cold_start_fallback:
      class_name: sample_popular_file
      item_file: popular_generic.csv
    cold_user_fallback:
      class_name: most_popular

  - name: Niche
    class_name: item_knn_cold
    min_neighbors: 1
    max_neighbors: 20
    min_similarity: 0.001

triggers:
  - name: Cycle5Freeze
    class_name: initial_burnin
    params:
      cycle_count: 5


