# Sample SMORES configuration

simulation:
    experiment_name: test_experiment
    num_days: 10
    num_cycles: 10
    slate_size: 5
    seed: 20250513

data:
  directory: data/raw/ambar
  consumer_file: users.csv
  item_file: items.csv
  provider_file: artists.csv`

consumers:
  - profile_name: mainstream
    ratio: 0.7
    recommender_assignment:
      class_name: fixed
      name: Generic
    utility_model:
      class_name: list_average
    item_selection_model:
      class_name: category_similarity_logit
      threshold: 0.3
    recommender_choice_model:
      class_name: threshold
      threshold: 0.1

  - profile_name: niche
    ratio: 0.3
    recommender_assignment:
      class_name: fixed
      name: Niche
    utility_model:
      class_name: list_average
    item_selection_model:
      class_name: category_similarity_logit
      threshold: 0.2
    recommender_choice_model:
      class_name: threshold
      threshold: 0.05

providers:
  - profile_name: mainstream_provider
    ratio: 0.9
    utility_model:
      class_name: click_fixed
      value: 1

  - profile_name: niche_provider
    ratio: 0.1
    utility_model:
      class_name: click_fixed
      value: 1.5

platform:
  utility_model:
    class_name: null_model

recommenders:
  - name: Generic
    class_name: svd_generic

  - name: Niche
    class_name: niche

triggers:
  - name: Cycle5Freeze
    class_name: initial_burnin
    cycle_count: 5


